### ISSUE TITLE
Issue with "Is" functions

### ISSUE THREAD

**Issue by mtiller** [joanllenas/ts.data.maybe#3]
This is a very nice library.  But one issue I came across was the fact that `isNothing` and `isJust` are defined as:

```typescript```
export declare const isJust: <T>(value: Maybe<T>) => boolean;
export declare const isNothing: <T>(value: Maybe<T>) => boolean;
```

...when it would be much better if they were defined as:

```typescript
export declare const isJust: <T>(value: Maybe<T>) => value is Just<T>;
export declare const isNothing: <T>(value: Maybe<T>) => value is Nothing;
```

This would allow type narrowing.  Unfortunately, I can't write these myself because of another issue which is that you don't export the types for Just and Nothing.  So they can't be referred to outside the package.  I realized that I can use `caseOf` as well to narrow types, sometimes it is better to do this in an imperative vs. functional way (although I appreciate the option).

**Comment by joanllenas** [comment]
Hi @mtiller ,
very nice suggestion!
Released here: https://github.com/joanllenas/ts.data.maybe/releases/tag/v2.2.1

Cheers!
